/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu.proyecto;

import java.awt.Image;
import java.io.IOException;
import java.io.InputStream;
import java.util.LinkedList;
import java.util.Queue;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author 52999
 */
public class Impresora extends javax.swing.JFrame {
    
    Queue cola = new LinkedList();
    private ImageIcon imagen;
    private Icon icono;
    private int posicion;

    /**
     * Creates new form Impresora
     */
    public Impresora() {
        initComponents();
        
        this.insertarImagen(this.lblPC1, "/com/mycompany/impresora/imagenes/PC1.jpg");
        this.insertarImagen(this.lblPC2, "/com/mycompany/impresora/imagenes/PC2.jpg");
        this.insertarImagen(this.lblPC3, "/com/mycompany/impresora/imagenes/PC3.jpg");
        this.insertarImagen(this.lblPC4, "/com/mycompany/impresora/imagenes/PC4.jpg");
        this.insertarImagen(this.lblPC5, "/com/mycompany/impresora/imagenes/PC5.jpg");        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPC1 = new javax.swing.JLabel();
        lblPC2 = new javax.swing.JLabel();
        lblPC3 = new javax.swing.JLabel();
        lblPC4 = new javax.swing.JLabel();
        lblPC5 = new javax.swing.JLabel();
        cola1 = new javax.swing.JLabel();
        txtImprimiendo = new javax.swing.JLabel();
        cola2 = new javax.swing.JLabel();
        cola3 = new javax.swing.JLabel();
        cola4 = new javax.swing.JLabel();
        cola5 = new javax.swing.JLabel();
        cola6 = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        txtPCImprimiendo = new javax.swing.JLabel();
        txtColadeImpresión = new javax.swing.JLabel();
        btnAgregar1 = new javax.swing.JButton();
        btnAgregar2 = new javax.swing.JButton();
        btnAgregar3 = new javax.swing.JButton();
        btnAgregar4 = new javax.swing.JButton();
        btnAgregar5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(119, 167, 151));

        lblPC1.setBackground(new java.awt.Color(255, 255, 255));
        lblPC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PC1.jpg"))); // NOI18N

        lblPC2.setBackground(new java.awt.Color(255, 255, 255));
        lblPC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PC2.jpg"))); // NOI18N

        lblPC3.setBackground(new java.awt.Color(255, 255, 255));
        lblPC3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PC3.jpg"))); // NOI18N

        lblPC4.setBackground(new java.awt.Color(255, 255, 255));
        lblPC4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PC4.jpg"))); // NOI18N

        lblPC5.setBackground(new java.awt.Color(255, 255, 255));
        lblPC5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PC5.jpg"))); // NOI18N

        cola1.setBackground(new java.awt.Color(255, 255, 255));
        cola1.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        cola1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cola1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(17, 118, 84)));

        txtImprimiendo.setBackground(new java.awt.Color(255, 255, 255));
        txtImprimiendo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        txtImprimiendo.setText("Se está imprimiendo");
        txtImprimiendo.setToolTipText("");

        cola2.setBackground(new java.awt.Color(255, 255, 255));
        cola2.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        cola2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cola2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(17, 118, 84)));

        cola3.setBackground(new java.awt.Color(255, 255, 255));
        cola3.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        cola3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cola3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(17, 118, 84)));

        cola4.setBackground(new java.awt.Color(255, 255, 255));
        cola4.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        cola4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cola4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(17, 118, 84)));

        cola5.setBackground(new java.awt.Color(255, 255, 255));
        cola5.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        cola5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cola5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(17, 118, 84)));

        cola6.setBackground(new java.awt.Color(255, 255, 255));
        cola6.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        cola6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cola6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(17, 118, 84)));

        btnImprimir.setBackground(new java.awt.Color(111, 163, 111));
        btnImprimir.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        txtPCImprimiendo.setBackground(new java.awt.Color(255, 255, 255));
        txtPCImprimiendo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        txtPCImprimiendo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtColadeImpresión.setBackground(new java.awt.Color(255, 255, 255));
        txtColadeImpresión.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        txtColadeImpresión.setText("Cola de Impresión");
        txtColadeImpresión.setToolTipText("");

        btnAgregar1.setBackground(new java.awt.Color(79, 172, 172));
        btnAgregar1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnAgregar1.setText("Agregar");
        btnAgregar1.setBorder(null);
        btnAgregar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        btnAgregar2.setBackground(new java.awt.Color(79, 172, 172));
        btnAgregar2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnAgregar2.setText("Agregar");
        btnAgregar2.setBorder(null);
        btnAgregar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar2ActionPerformed(evt);
            }
        });

        btnAgregar3.setBackground(new java.awt.Color(79, 172, 172));
        btnAgregar3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnAgregar3.setText("Agregar");
        btnAgregar3.setBorder(null);
        btnAgregar3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar3ActionPerformed(evt);
            }
        });

        btnAgregar4.setBackground(new java.awt.Color(79, 172, 172));
        btnAgregar4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnAgregar4.setText("Agregar");
        btnAgregar4.setBorder(null);
        btnAgregar4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar4ActionPerformed(evt);
            }
        });

        btnAgregar5.setBackground(new java.awt.Color(79, 172, 172));
        btnAgregar5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnAgregar5.setText("Agregar");
        btnAgregar5.setBorder(null);
        btnAgregar5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar5ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(79, 172, 172));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(txtColadeImpresión, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(120, 120, 120)
                .addComponent(txtImprimiendo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(cola6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cola5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cola4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cola3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cola2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cola1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(txtPCImprimiendo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblPC1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(lblPC2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPC3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPC4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPC5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnAgregar3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnAgregar4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnAgregar5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cola1, cola2, cola3, cola4, cola5, cola6});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPC5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPC1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPC2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPC3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPC4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColadeImpresión, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImprimiendo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPCImprimiendo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(cola2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(cola1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cola3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cola4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cola5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cola6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnImprimir)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void insertarImagen(JLabel label, String ruta) {
        try {
        // Cargar la imagen desde el classpath
            InputStream is = getClass().getResourceAsStream(ruta);
            if (is != null) {
                imagen = new ImageIcon(ImageIO.read(is));
                icono = new ImageIcon(imagen.getImage().getScaledInstance(
                    label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH));
                label.setIcon(icono);
            } else {
                System.err.println("No se encontró la imagen en la ruta: " + ruta);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    
    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        txtPCImprimiendo.setText("");
        if (!cola.isEmpty()){
            txtPCImprimiendo.setText(imprimirValor());
            imprimirCola();
        } else {
            JOptionPane.showMessageDialog(null, "La cola está vacia");
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
       
        if (cola.size()<6){
            cola.add("PC1");
        } else {
            JOptionPane.showMessageDialog(null, "La cola de impresión está llena");
        }
        imprimirCola();
        
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar2ActionPerformed

        if (cola.size()<6){
            cola.add("PC2");
        } else {
            JOptionPane.showMessageDialog(null, "La cola de impresión está llena");
        }
        imprimirCola();
    }//GEN-LAST:event_btnAgregar2ActionPerformed

    private void btnAgregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar3ActionPerformed
        if (cola.size()<6){
            cola.add("PC3");
        } else {
            JOptionPane.showMessageDialog(null, "La cola de impresión está llena");
        }
        imprimirCola();
    }//GEN-LAST:event_btnAgregar3ActionPerformed

    private void btnAgregar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar4ActionPerformed
        if (cola.size()<6){
            cola.add("PC4");
        } else {
            JOptionPane.showMessageDialog(null, "La cola de impresión está llena");
        }
        imprimirCola();
    }//GEN-LAST:event_btnAgregar4ActionPerformed

    private void btnAgregar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar5ActionPerformed
        if (cola.size()<6){
            cola.add("PC5");
        } else {
            JOptionPane.showMessageDialog(null, "La cola de impresión está llena");
        }
        imprimirCola();
    }//GEN-LAST:event_btnAgregar5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Mainmenu v0 = new Mainmenu();
        v0.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private String imprimirValor() {
        if (!cola.isEmpty()) {
            return String.valueOf(cola.poll()); // Convierte el elemento eliminado en String y lo retorna
        } else {
            return "La cola está vacía."; // Mensaje en caso de que la cola esté vacía
        }
    }
    
    private void imprimirCola(){
        cola1.setText(leerPosicion(0));
        cola2.setText(leerPosicion(1));
        cola3.setText(leerPosicion(2));
        cola4.setText(leerPosicion(3));
        cola5.setText(leerPosicion(4));
        cola6.setText(leerPosicion(5));
    }

    private String leerPosicion(int posicion) {
        int indice = 0;
        for (Object elemento : cola) { // Itera directamente sobre los elementos de la cola
            if (indice == posicion) {
                return String.valueOf(elemento); // Retorna el elemento convertido a String
            }
            indice++;
        }

    return null; // Esto nunca se alcanza, pero se incluye por estructura
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Impresora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnAgregar2;
    private javax.swing.JButton btnAgregar3;
    private javax.swing.JButton btnAgregar4;
    private javax.swing.JButton btnAgregar5;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel cola1;
    private javax.swing.JLabel cola2;
    private javax.swing.JLabel cola3;
    private javax.swing.JLabel cola4;
    private javax.swing.JLabel cola5;
    private javax.swing.JLabel cola6;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPC1;
    private javax.swing.JLabel lblPC2;
    private javax.swing.JLabel lblPC3;
    private javax.swing.JLabel lblPC4;
    private javax.swing.JLabel lblPC5;
    private javax.swing.JLabel txtColadeImpresión;
    private javax.swing.JLabel txtImprimiendo;
    private javax.swing.JLabel txtPCImprimiendo;
    // End of variables declaration//GEN-END:variables
}
