/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu.proyecto;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.JLabel;
import java.io.IOException;

/**
 *
 * @author Miguel Angel Espinosa de los Monteros Osuna, Aletxa Pascual Macias, Juliette
 * 
 */
public class Mainmenu extends javax.swing.JFrame {

    /**
     * Creates new form Mainmenu
     */ 
    boolean a = true;
    
    public Mainmenu() {
        initComponents();
        Gato.setVisible(false);
        Home.setVisible(true);
        Cola.setVisible(false);
        Hanoi.setVisible(false);
        Arbol.setVisible(false);
        Postres.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    public void changecolorB(JButton hover, Color rand){
        hover.setBackground(rand);
    }
    
    public void hideshow(JPanel menushowhide, boolean dashboard, JLabel button){
        if (dashboard == true){
            menushowhide.setPreferredSize(new Dimension(270, menushowhide.getHeight()));
            changeimage(button, "/Icon/back_32px.png");
        }
        else{
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
            changeimage(button, "/Icon/menu_32px.png");
        }
    
    }
    
    public void changeimage(JLabel button, String resourcheimg){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheimg));
        button.setIcon(aimg);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        iconminmax = new javax.swing.JPanel();
        btnmin = new javax.swing.JPanel();
        btnclose = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        btnmax = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JPanel();
        linehide = new javax.swing.JPanel();
        btnhide = new javax.swing.JPanel();
        hide = new javax.swing.JLabel();
        menuhide = new javax.swing.JPanel();
        btnPostres = new javax.swing.JButton();
        btnArbol = new javax.swing.JButton();
        btnHanoi = new javax.swing.JButton();
        btnGato = new javax.swing.JButton();
        btnCola = new javax.swing.JButton();
        dashboard = new javax.swing.JPanel();
        Postres = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Arbol = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Cola = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Gato = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Hanoi = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        header.setBackground(new java.awt.Color(5, 10, 46));
        header.setPreferredSize(new java.awt.Dimension(800, 50));
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                headerMouseClicked(evt);
            }
        });
        header.setLayout(new java.awt.BorderLayout());

        iconminmax.setBackground(new java.awt.Color(5, 10, 46));
        iconminmax.setPreferredSize(new java.awt.Dimension(150, 50));

        btnmin.setBackground(new java.awt.Color(5, 10, 46));
        btnmin.setPreferredSize(new java.awt.Dimension(50, 50));
        btnmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnclose.setBackground(new java.awt.Color(5, 10, 46));
        btnclose.setPreferredSize(new java.awt.Dimension(50, 50));
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
        });

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete_32px.png"))); // NOI18N
        close.setMaximumSize(new java.awt.Dimension(50, 50));
        close.setMinimumSize(new java.awt.Dimension(50, 50));
        close.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout btncloseLayout = new javax.swing.GroupLayout(btnclose);
        btnclose.setLayout(btncloseLayout);
        btncloseLayout.setHorizontalGroup(
            btncloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btncloseLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        btncloseLayout.setVerticalGroup(
            btncloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnmax.setBackground(new java.awt.Color(5, 10, 46));
        btnmax.setPreferredSize(new java.awt.Dimension(50, 50));
        btnmax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmaxMouseExited(evt);
            }
        });
        btnmax.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Home.png"))); // NOI18N
        btnmax.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        javax.swing.GroupLayout iconminmaxLayout = new javax.swing.GroupLayout(iconminmax);
        iconminmax.setLayout(iconminmaxLayout);
        iconminmaxLayout.setHorizontalGroup(
            iconminmaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, iconminmaxLayout.createSequentialGroup()
                .addComponent(btnmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        iconminmaxLayout.setVerticalGroup(
            iconminmaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        header.add(iconminmax, java.awt.BorderLayout.LINE_END);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        menu.setPreferredSize(new java.awt.Dimension(50, 450));
        menu.setLayout(new java.awt.BorderLayout());

        MenuIcon.setBackground(new java.awt.Color(5, 10, 46));
        MenuIcon.setPreferredSize(new java.awt.Dimension(50, 450));
        MenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linehide.setBackground(new java.awt.Color(5, 10, 46));

        javax.swing.GroupLayout linehideLayout = new javax.swing.GroupLayout(linehide);
        linehide.setLayout(linehideLayout);
        linehideLayout.setHorizontalGroup(
            linehideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linehideLayout.setVerticalGroup(
            linehideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(linehide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 5));

        btnhide.setBackground(new java.awt.Color(5, 10, 46));
        btnhide.setLayout(new java.awt.BorderLayout());

        hide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/menu_32px.png"))); // NOI18N
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hideMouseExited(evt);
            }
        });
        btnhide.add(hide, java.awt.BorderLayout.CENTER);

        MenuIcon.add(btnhide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, 50));

        menu.add(MenuIcon, java.awt.BorderLayout.LINE_START);

        menuhide.setBackground(new java.awt.Color(25, 29, 74));
        menuhide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPostres.setBackground(new java.awt.Color(33, 63, 147));
        btnPostres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPostres.setForeground(new java.awt.Color(255, 255, 255));
        btnPostres.setText("Postres");
        btnPostres.setBorder(null);
        btnPostres.setBorderPainted(false);
        btnPostres.setDefaultCapable(false);
        btnPostres.setFocusPainted(false);
        btnPostres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPostresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPostresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPostresMouseExited(evt);
            }
        });
        menuhide.add(btnPostres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 34));

        btnArbol.setBackground(new java.awt.Color(33, 63, 147));
        btnArbol.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnArbol.setForeground(new java.awt.Color(255, 255, 255));
        btnArbol.setText("Árbol Binario");
        btnArbol.setBorder(null);
        btnArbol.setBorderPainted(false);
        btnArbol.setFocusPainted(false);
        btnArbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnArbolMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnArbolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnArbolMouseExited(evt);
            }
        });
        menuhide.add(btnArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 72, 220, 34));

        btnHanoi.setBackground(new java.awt.Color(33, 63, 147));
        btnHanoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHanoi.setForeground(new java.awt.Color(255, 255, 255));
        btnHanoi.setText("Torre Hanoi");
        btnHanoi.setBorder(null);
        btnHanoi.setBorderPainted(false);
        btnHanoi.setFocusPainted(false);
        btnHanoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHanoiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHanoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHanoiMouseExited(evt);
            }
        });
        menuhide.add(btnHanoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 124, 220, 34));

        btnGato.setBackground(new java.awt.Color(33, 63, 147));
        btnGato.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGato.setForeground(new java.awt.Color(255, 255, 255));
        btnGato.setText("Tic Tac Toe");
        btnGato.setBorder(null);
        btnGato.setBorderPainted(false);
        btnGato.setFocusPainted(false);
        btnGato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGatoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGatoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGatoMouseExited(evt);
            }
        });
        btnGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGatoActionPerformed(evt);
            }
        });
        menuhide.add(btnGato, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 176, 220, 34));

        btnCola.setBackground(new java.awt.Color(33, 63, 147));
        btnCola.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCola.setForeground(new java.awt.Color(255, 255, 255));
        btnCola.setText("Cola de Impresiones");
        btnCola.setBorder(null);
        btnCola.setBorderPainted(false);
        btnCola.setFocusPainted(false);
        btnCola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnColaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnColaMouseExited(evt);
            }
        });
        menuhide.add(btnCola, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 220, 34));

        menu.add(menuhide, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        dashboard.setBackground(new java.awt.Color(73, 128, 242));
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Postres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(192, 222, 253));
        jButton5.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jButton5.setText("Iniciar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Postres.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 130, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Postress.png"))); // NOI18N
        Postres.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        dashboard.add(Postres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        Arbol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(192, 222, 253));
        jButton3.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jButton3.setText("Iniciar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Arbol.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 130, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Árbol Binario (1).png"))); // NOI18N
        Arbol.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 750, 450));

        dashboard.add(Arbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        Cola.setMinimumSize(new java.awt.Dimension(750, 450));
        Cola.setPreferredSize(new java.awt.Dimension(750, 450));
        Cola.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(192, 222, 253));
        jButton2.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jButton2.setText("Iniciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Cola.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 130, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cola.png"))); // NOI18N
        Cola.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        dashboard.add(Cola, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Gato.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(192, 222, 253));
        jButton1.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jButton1.setText("Iniciar");
        jButton1.setToolTipText("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Gato.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 130, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/gato.png"))); // NOI18N
        Gato.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dashboard.add(Gato, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Hanoi.setPreferredSize(new java.awt.Dimension(750, 450));
        Hanoi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(192, 222, 253));
        jButton4.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jButton4.setText("Iniciar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Hanoi.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 130, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Hanoi (1).png"))); // NOI18N
        Hanoi.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 750, 460));

        dashboard.add(Hanoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/MENUU.png"))); // NOI18N
        Home.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dashboard.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(dashboard, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(800, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**PARA CERRAR
     */
    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btncloseMouseClicked

    private void btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseEntered
        changecolor(btnclose, new Color(25, 29, 74));
    }//GEN-LAST:event_btncloseMouseEntered

    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        changecolor(btnclose, new Color(5, 10, 46));
    }//GEN-LAST:event_btncloseMouseExited

    
    /**PARA MAXIMIZAR
     */
    private void btnmaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmaxMouseClicked
        Gato.setVisible(false);
        Home.setVisible(true);
        Cola.setVisible(false);
        Hanoi.setVisible(false);
        Arbol.setVisible(false);
        Postres.setVisible(false);
    }//GEN-LAST:event_btnmaxMouseClicked

    private void btnmaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmaxMouseEntered
        changecolor(btnmax, new Color(25, 29, 74));
    }//GEN-LAST:event_btnmaxMouseEntered

    private void btnmaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmaxMouseExited
         changecolor(btnmax, new Color(5, 10, 46));
    }//GEN-LAST:event_btnmaxMouseExited

    /**PARA MOSTRAR O ESCONDER MENU
     */
    private void hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseClicked

            if (a==true){
                hideshow(menu, a, hide);
                SwingUtilities.updateComponentTreeUI(this);
                a=false;
            }
            else{
                hideshow(menu, a, hide);
                SwingUtilities.updateComponentTreeUI(this);
                a=true;
            }
            
            
    }//GEN-LAST:event_hideMouseClicked

    private void hideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseEntered
        changecolor(linehide, new Color(247, 78, 105));
        changecolor(btnhide, new Color(25, 29, 74));
    }//GEN-LAST:event_hideMouseEntered

    private void hideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseExited
        changecolor(linehide, new Color(5, 10, 46));
        changecolor(btnhide, new Color(5, 10, 46));
    }//GEN-LAST:event_hideMouseExited

    
    /**
     * POSTRES 
     */ 
    private void btnPostresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPostresMouseClicked
        hideshow(menu, a, hide);
        SwingUtilities.updateComponentTreeUI(this);
        Gato.setVisible(false);
        Home.setVisible(false);
        Cola.setVisible(false);
        Hanoi.setVisible(false);
        Arbol.setVisible(false);
        Postres.setVisible(true);
    }//GEN-LAST:event_btnPostresMouseClicked

    private void btnPostresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPostresMouseEntered
        changecolorB(btnPostres, new Color(51,153,255));
    }//GEN-LAST:event_btnPostresMouseEntered

    private void btnPostresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPostresMouseExited
        changecolorB(btnPostres, new Color(33,63,147));
    }//GEN-LAST:event_btnPostresMouseExited
 /**
     * ARBOL
     */ 
    private void btnArbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArbolMouseClicked
        hideshow(menu, a, hide);
        SwingUtilities.updateComponentTreeUI(this);
        Gato.setVisible(false);
        Home.setVisible(false);
        Cola.setVisible(false);
        Hanoi.setVisible(false);
        Arbol.setVisible(true);
        Postres.setVisible(false);
    }//GEN-LAST:event_btnArbolMouseClicked

    private void btnArbolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArbolMouseEntered
        changecolorB(btnArbol, new Color(51,153,255));
    }//GEN-LAST:event_btnArbolMouseEntered

    private void btnArbolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArbolMouseExited
        changecolorB(btnArbol, new Color(33,63,147));
    }//GEN-LAST:event_btnArbolMouseExited
 /**
     * HANOI
     */ 
    private void btnHanoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHanoiMouseClicked
        hideshow(menu, a, hide);
        SwingUtilities.updateComponentTreeUI(this);
        Gato.setVisible(false);
        Home.setVisible(false);
        Cola.setVisible(false);
        Hanoi.setVisible(true);
        Arbol.setVisible(false);
        Postres.setVisible(false);
    }//GEN-LAST:event_btnHanoiMouseClicked

    private void btnHanoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHanoiMouseEntered
        changecolorB(btnHanoi, new Color(51,153,255));
    }//GEN-LAST:event_btnHanoiMouseEntered

    private void btnHanoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHanoiMouseExited
        changecolorB(btnHanoi, new Color(33,63,147));
    }//GEN-LAST:event_btnHanoiMouseExited
/**
     * TIC TAC TOE
     */ 
    private void btnGatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGatoMouseClicked
        hideshow(menu, a, hide);
        SwingUtilities.updateComponentTreeUI(this);
        Gato.setVisible(true);
        Home.setVisible(false);
        Cola.setVisible(false);
        Hanoi.setVisible(false);
        Arbol.setVisible(false);
        Postres.setVisible(false);
    }//GEN-LAST:event_btnGatoMouseClicked

    private void btnGatoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGatoMouseEntered
        changecolorB(btnGato, new Color(51,153,255));
    }//GEN-LAST:event_btnGatoMouseEntered

    private void btnGatoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGatoMouseExited
        changecolorB(btnGato, new Color(33,63,147));
    }//GEN-LAST:event_btnGatoMouseExited

    private void btnColaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColaMouseClicked
        hideshow(menu, a, hide);
        SwingUtilities.updateComponentTreeUI(this);
        Gato.setVisible(false);
        Home.setVisible(false);
        Cola.setVisible(true);
        Hanoi.setVisible(false);
        Arbol.setVisible(false);
        Postres.setVisible(false);
    }//GEN-LAST:event_btnColaMouseClicked

    private void btnColaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColaMouseEntered
        changecolorB(btnCola, new Color(51,153,255));
    }//GEN-LAST:event_btnColaMouseEntered

    private void btnColaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColaMouseExited
        changecolorB(btnCola, new Color(33,63,147));
    }//GEN-LAST:event_btnColaMouseExited

    private void btnGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGatoActionPerformed
        
        
    }//GEN-LAST:event_btnGatoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        Postre v2 = new Postre();
        v2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Main v3 = new Main();
        v3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Main v3 = new Main();
        v3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        HanoiGraphics v4 = new HanoiGraphics();
        v4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Impresora v5 = new Impresora();
        v5.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void headerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_headerMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String pythonFile = "src\\menu\\proyecto\\tictactoe.py"; // Chemin relatif vers le fichier Python

        try {
            // Créer un processus pour exécuter le script Python
            ProcessBuilder pb = new ProcessBuilder("python", pythonFile); // Utiliser "python3" si nécessaire
            pb.inheritIO(); // Permet de rediriger l'entrée/sortie du processus
            Process process = pb.start(); // Démarre le processus
            process.waitFor(); // Attend que le processus se termine
        } catch (IOException | InterruptedException e) {
            // En cas d'erreur, on imprime la pile d'erreurs
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1MouseClicked
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Arbol;
    private javax.swing.JPanel Cola;
    private javax.swing.JPanel Gato;
    private javax.swing.JPanel Hanoi;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JPanel Postres;
    private javax.swing.JButton btnArbol;
    private javax.swing.JButton btnCola;
    private javax.swing.JButton btnGato;
    private javax.swing.JButton btnHanoi;
    private javax.swing.JButton btnPostres;
    private javax.swing.JPanel btnclose;
    private javax.swing.JPanel btnhide;
    private javax.swing.JPanel btnmax;
    private javax.swing.JPanel btnmin;
    private javax.swing.JLabel close;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel header;
    private javax.swing.JLabel hide;
    private javax.swing.JPanel iconminmax;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel linehide;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuhide;
    // End of variables declaration//GEN-END:variables




}
